### ISSUE TITLE
Libcompose 1.0.0 <-> Compose 1.6.0 features

### ISSUE THREAD

**Issue by vdemeester** [docker/libcompose#124]
I've tried to come up with a *feature grid* / *missing feature* recap' in order to know what to do to achieve a complete compatibility with `docker-compose` ; and thus making it easy to follow afterwards.

The goal of this issue is to keep track of what is done and what's not. As it might be a little big, we'll probably split this up into small issues for each missing part.

I've created a `1.0.0` milestone (with a cool name I think :stuck_out_tongue_closed_eyes:) to start having some goals and helping us to focus. I also want to follow the releases of the other docker projects (but that's another story).

Anyway, this is what I've got so far. Note there is some stuff that are present in `libcompose` but not in `docker-compose`. 

ping @docker/libcompose-maintainers @ibuildthecloud @imikushin for feedback.
I probably missed some stuff so, let me know :wink:.

---

# Composefile

## Reference (v1)

- [x] `build`
- [x] `cap_add`, `cap_drop`
- [x] `command`
- [x] `cgroup_parent` #134 (PR)
- [x] `container_name`
- [x] `devices`
- [x] `dns`
- [x] `dns_search`
- [x] `dockerfile`
- [x] `env_file`
- [x] `environment`
- [x] `expose`
- [x] `extends`
- [x] `external_links`
- [x] `extra_hosts`
- [x] `image`
- [x] `labels`
- [x] `links`
- [x] `log_driver`
- [x] `log_opt`
- [x] `net`
- [x] `pid`
- [x] `ports`
- [x] `security_opt`
- [x] `ulimits` #134 (PR)
- [x] `volumes`, `volume_driver`
- [x] `volumes_from`
- [x] `cpu_shares`
- [x] `cpu_quota` #134 (PR)
- [x] `cpuset`
- [x] `domainname`
- [x] `entrypoint`
- [x] `hostname`
- [x] `ipc`
- [x] `mac_address` #134 (PR)
- [x] `mem_limit`
- [x] `memswap_limit`
- [x] `privileged`
- [x] `read_only`
- [x] `restart`
- [x] `stdin_open`
- [x] `tty`
- [x] `user`
- [x] `working_dir`

- [ ] `uts` not supported in `docker-compose` ?

## Reference (v2)

To support :angel: 

# CLI

### Commands

- [x] build
    - [x] `--no-cache`
    - [ ] `--pull`
    - [ ] `--force-rm`
- [ ] config
    - [ ] `-q, --quiet`
    - [ ] `--services`
- [x] `create`
    - [X] `--force-recreate` #135
    - [X] `--no-recreate` #135
    - [x] `--no-build` #136
- [x] `down` (currently an alias to stop)
    - [x]  see docker-compose down docker/compose#2646 
- [x] help
    - [ ] Some help are not working properly (e.g. `libcompose-cli
      help build`) — carry #102.
- [x] kill
    - [x] `-s SIGNAL` (`libcompose-cli` supports `--signal`)
- [x] logs
    - [ ] `--no-color`
    - [ ] `--lines` support by `libcompose-cli` but not by `docker-compose`
- [x] pause #128 (PR)
- [x] port
    - [x] `--protocol=proto`
    - [x] `--index=index`
- [x] ps
    - [x] `-q`
- [x] pull
    - [ ] `--ignore-pull-failures`
    - [x] `--allow-insecure-ssl` deprecated, won't add.
- [x] restart
    - [x] `-t, --timeout TIMEOUT`
- [x] rm #129 (issue), #130 (PR)
    - [x] `-f, --force`
    - [x] `-v`
- [x] run #38 (issue), <del>#45</del> #133 (PR)
    - [x] `--allow-insecure-ssl` deprecated, won't add.
    - [ ] `-d`
    - [ ] `--name NAME`
    - [ ] `--entrypoint CMD`
    - [ ] `-e KEY=VAL`
    - [ ] `-u, --user=""`
    - [ ] `--no-deps`
    - [ ] `--rm`
    - [ ] `-p, --publish=[]`
    - [ ] `--service-ports`
    - [ ] `-T`
- [x] scale
    - [x] `-t, --timeout TIMEOUT`
- [x] start
    - [x] `-d` support by `libcompose-cli` but not by `docker-compose`
- [x] stop
    - [x] `-t, --timeout TIMEOUT`
- [x] unpause #128 (PR)
- [x] up
    - [x] `--allow-insecure-ssl` deprecated, won't add.
    - [x] `-d`
    - [ ] `--no-color`
    - [ ] `--no-deps`
    - [x] `--force-recreate`
    - [x] `--no-recreate`
    - [x] `--no-build` #136
    - [ ] `-t, --timeout TIMEOUT`
- [x] migrate-to-labels: to implement ?
- [x] version
    - [ ] `--short`

### Global flags

- [x] `-f, --file FILE`
- [x] `-p, --project-name NAME`
- [x] `--x-networking`
- [x] `--x-network-driver`
- [x] `--verbose` is also `--debug` on `libcompose-cli`
- [x] `-v, --version`

- [ ] TLS related flags (`--tls`, `--tlsverify`, `--tlscacert`,
  `--tlscert`, `--tlskey`) : how it is handled in `docker-compose` (compose#1569)
- [ ] `--configdir`
- [ ] `--help, -h` should move to `help` only ?
- [ ] `--version, -v` should move to `version` only

## Environment Variables

- [x] `COMPOSE_PROJECT_NAME`
- [X] `COMPOSE_FILE`
- [ ] `COMPOSE_API_VERSION`
- [x] `DOCKER_*` (`DOCKER_HOST`, `DOCKER_TLS_VERIFY`,
  `DOCKER_CERT_PATH`, `COMPOSE_HTTP_TIMEOUT`)

# Miscellaneous

- [x] yaml schema validation #34 (issue) and #99 (PR)
- [ ] Refactor flag system (switch to cobra or …) ?
- [ ] completion support ? (probably re-use docker-compose one but…)
- [x] `docker-compose up -d` then `libcompose-cli ps` doesn't work >_<, see issue #132
- [ ] What to do about the `warn` message
- [ ] not allow `restart: no` but require `restart: 'no'` #72
- [x] multiple file (`-f` and `docker-compose.override.yml`) #116
- [ ] Preserve volume data when containers are created
- [x] Only recreate containers that have changed
- [x] Variables and moving a composition between environments
- [x] Support multiple version of `compose.yml` (with key `version: 2`), see docker/compose#2421

# Maybe

Those are in discussion / review on `docker-compose` so as long as they are not merged or completely sure to get in 1.6.0, it probably shouldn't be in 1.0.0 of libcompose. I'll create issues to track them down.

- [ ] Epic: Backwards-incompatible changes to the Compose file format docker/compose#2504 
  - [ ] Proposal: Make `net` and `volumes_from`'s container/service support explicit docker/compose#2501 
  - [ ] Move logging configuration under `logging` key docker/compose#2503 
  - [x] Proposal: new build config section docker/compose#2163 
  - [x] Image and build together docker/compose#2458 
- [ ] Epic: Support Docker's new networking model docker/compose#1803 
  - [ ] Specify networks in the Compose file - docker/compose#2478
  - [ ] Move network support out of experimental status and make it the default (or only) means of inter-service communication (see the Epic)
- [ ] docker-compose events docker/compose#2392 
- [x] Add support for declaring named volumes in compose files docker/compose#2421 
- [x] Improvements to `docker-compose logs` docker/compose#2227 (new flags and updates to the `logs` command)
- [ ]  Proposal: make project-name persistent. docker/compose#745

**Comment by ibuildthecloud** [comment]
@vdemeester Wow, thanks, this is really helpful.  I'll look over it more next year (next week :smile: )

**Comment by vdemeester** [comment]
I still have to list some stuff that would be in the 1.6.0 milestone for `docker-compose`, see https://github.com/docker/compose/milestones/1.6.0.

**Comment by F21** [comment]
The `--x-networking` flag is now removed. Networks are now automatically created by default: https://docs.docker.com/compose/networking/

**Comment by vdemeester** [comment]
@F21 Thanks :-) I need to close this issue and split it up to be able to follow the gap and progress better ;-)
