### ISSUE TITLE
Enhance test coverage

### ISSUE THREAD

**Issue by vdemeester** [docker/libcompose#327]
Taking comment from #316:

> - Any package should be small and heavily tested. If it's not easy to write test, then it needs refactoring :angel:.
> - There should be way more unit tests than integration tests. And Integration tests on `libcompose` should focus on the API side. (_Note: I'm thinking of trying out `convey` as a lib to write tests, as an experiment :angel:_)
> - We should have almost no integration tests for the `cli` side as they should be handled by the acceptance tests suite comming from `docker/compose` :wink: 

There is 3 axes : unit testing, integration testing and acceptance testing
- [ ] Increase unit coverage : we should have way more unit test than anything else.
  - If something is hard to test, let's refactor it to make it easier to test :sweat_smile: 
  - If we feel some thing should be isolated in package (for more compsability), let's do it too (e.g. package `docker` should have `container`, `service`, … sub package).
- [ ] Migrate most cli tests from `integration` tests to api/lib tests
- [ ] Make `test-acceptance` 100% green (and thus not ignoring it in the builds :angel:)
